### ISSUE TITLE
add json format for the spec

### ISSUE THREAD

**Issue by ssbarnea** [build-canaries/cctray#7]
The spec should also provide a JSON format which is much easier to parse by everyone, browsers, humans, ...

**Comment by GentlemanHal** [comment]
Hi @ssbarnea, thanks for raising this issue!

I agree a JSON format would be much easier to work with, the main issue would be getting server implementors to support it.

There has been another effort to create a JSON format, called the CatLight protocol https://catlight.helprace.com/i240-monitor-any-build-server-using-catlight-protocol

I'm not sure how popular it is or how they went about trying to get servers to implement it.

**Comment by joejag** [comment]
We plan on writing an updated version of the format which may very well be in JSON rather than XML. Perhaps `cc.xml` could be the legacy version ang `cc.json` be the new one. We might settle on that.

For the moment this site represents the historic and current state of the cctray format, which is XML

**Comment by GentlemanHal** [comment]
Although I agree having a JSON format for the spec is a great idea, we aren't realistically going to add one anytime soon.
So I'm going to close this issue, as keeping it open isn't providing any value.
